<a href="https://colab.research.google.com/github/likeJoseph/helloworld/blob/master/(R)_002_Matrix_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://colab.research.google.com/notebook#create=true&language=r


# **R Matrix Exercises**

Through these exercises we will review the matrix data structure and perhaps introduce you to a few ideas for you to discover on your own! Just answer the questions below written in bold:

**Ex 1: Create 2 vectors A and B, where A is (1,2,3) and B is (4,5,6). With these vectors, use the cbind() or rbind() function to create a 2 by 3 matrix from the vectors. You'll need to figure out which of these binding functions is the correct choice.**

In [ ]:
A <- c(1,2,3)
B <- c(4,5,6)

rbind(A,B)

[,1] [,2] [,3]
A 1    2    3   
B 4    5    6

**Ex 2: Create a 3 by 3 matrix consisting of the numbers 1-9. Create this matrix using the shortcut 1:9 and by specifying the nrow argument in the matrix() function call. Assign this matrix to the variable mat**

In [ ]:
mat <- matrix(1:9, nrow = 3)

**Ex 3: Confirm that mat is a matrix using is.matrix()**

In [ ]:
is.matrix(mat)

[1] TRUE

**Ex 4: Create a 5 by 5 matrix consisting of the numbers 1-25 and assign it to the variable mat2. The top row should be the numbers 1-5.**

In [ ]:
mat2 <- matrix(1:25, 5, byrow = TRUE)
mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

**Ex 5: Using indexing notation, grab a sub-section of mat2 from the previous exercise that looks like this:**

[7,8]<br>
[12,13] 

In [ ]:
print(mat2[2:3, 2:3])

     [,1] [,2]
[1,]    7    8
[2,]   12   13


**Ex 6: Using indexing notation, grab a sub-section of mat2 from the previous exercise that looks like this:**

[19,20]<br>
[24,25]

In [ ]:
print(mat2[4:5, 4:5])

     [,1] [,2]
[1,]   19   20
[2,]   24   25


**Ex 7: What is the sum of all the elements in mat2?**

In [ ]:
sum(mat2)

[1] 325

**Ex 8: Ok time for our last exercise! Find out how to use runif() to create a 4 by 5 matrix consisting of 20 random numbers (4*5=20).**

In [ ]:
matrix(runif(20), nrow = 4)

[,1]      [,2]      [,3]      [,4]      [,5]     
[1,] 0.1620186 0.7919480 0.1750495 0.8312216 0.7887331
[2,] 0.1448891 0.5953602 0.1843555 0.5566000 0.1940169
[3,] 0.3004245 0.3559768 0.9668534 0.4022940 0.8567137
[4,] 0.8643322 0.1702851 0.8018412 0.9847127 0.9346575

**Great Job!**